# This is a basic workflow that is manually triggered
name: getcrl

on: 
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'get moica crl'
jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run script file
      run: |
         ls -al
         /gov-crl/getcrl.sh
      shell: bash
