# This is a basic workflow that is manually triggered
name: getcrl

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'get moica crl'
  schedule:
    - cron: '0 12,0 * * *'
jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run script file
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      run: |
         .github/getcrl.sh
         git add .
         git commit -m "update"
         git push 
      shell: bash
