# This is a basic workflow that is manually triggered
name: getcrl

on: 
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'get moica crl'
        required: true
jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Run script file
      run: |
         chmod +x ./getcrl.sh
         ./getcrl.sh
      shell: bash
