# This is a basic workflow that is manually triggered
name: getcrl

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'get moica crl'
  schedule:
    - cron: '0 12,0 * * *'
jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run script file
      run: |
         .github/getcrl.sh
         git config user.name "github-actions[bot]"
         git config user.email "github-actions[bot]@users.noreply.github.com"
         git add . && git commit -m "update" && git push -f
      shell: bash

